#!/usr/bin/perl

#
# nethserver-mail-user-cleanup
#
# Call the user-cleanup event
#

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::event;
use esmith::ConfigDB;

my $event = shift || die("Missing event argument!");
my $account = shift || die("Missing account name argument!");
my $db = esmith::ConfigDB->open_ro() or die("Could not open ConfigDB");

# preserve the data of deleted User
my $KeepUserData = $db->get_prop('data-cleanup','AsyncRemoval') || 'disabled';
exit 0 if ($KeepUserData eq 'enabled');

if( ! esmith::event::event_signal('user-cleanup',$account)) {
    die "ERROR: The event user-cleanup $account failed !!!";
}
