#!/usr/bin/perl

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::ConfigDB;

my $event = shift;
my $errors = 0;

if( ! -f '/var/lib/nethserver/vmail/vmail/Maildir/dovecot-acl' || $event eq '--force') {
    warn("[NOTICE] Initialize ACLs of Public (vmail) IMAP namespace\n");
    system('doveadm acl set -u vmail INBOX authenticated lookup');
    if($? != 0) {
        $errors++;
    }
    system('doveadm acl set -u vmail INBOX user=root admin create delete expunge insert lookup post read write write-deleted write-seen');
    if($? != 0) {
        $errors++;
    }
}

my $spamFolder = eval { esmith::ConfigDB->open_ro()->get_prop('dovecot', 'SpamFolder') || '' };
if($spamFolder) {
    my $spamPath = qx(doveadm mailbox path -u vmail $spamFolder);
    chomp($spamPath);
    if($spamPath && ! -d $spamPath) {
        system(qw(doveadm mailbox create -u vmail), $spamFolder);
    }
    if($spamPath && (! -f "$spamPath/dovecot-acl" || $event eq '--force')) {
        warn("[NOTICE] Initialize ACLs of public $spamFolder folder\n");
        system(qw(doveadm acl set -u vmail), $spamFolder, qw(user=root admin create delete expunge insert lookup post read write write-deleted write-seen));
        if($? != 0) {
            warn("[ERROR] Failed to set default ACL for public $spamFolder mailbox\n");
            $errors++;
        }
    }
}

exit ($errors == 0 ? 0 : 1);