#!/bin/bash
#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

arc=/var/lib/nethserver/backup/nethserver-mail-shrmbx.tar

rm -f $arc

cd /var/lib/nethserver/vmail

(
    echo shared-mailboxes.db
    echo vmail
    echo vmail/Maildir
    find vmail -type d \( -name cur -o -name new -o -name tmp -o -name '.*' \) -print \
        -o -type f \( -name dovecot-acl -o -name maildirfolder \) -print
) | tar --no-recursion -c -T - -f $arc
