#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

# skip event name

shift

# check if engine used is rsync

backup=$1
[ "$(/sbin/e-smith/db backups gettype "${backup}")" = "rsync" ] || exit 0

# if rsync then fix permissions

if [[ -d "/var/lib/nethserver/vmail/" && $(stat -c %U:%G "/var/lib/nethserver/vmail/") != "vmail:vmail" ]]; then
  /bin/chown -R vmail:vmail /var/lib/nethserver/vmail
  /bin/chgrp vmail /var/lib/nethserver/sieve-scripts
  /bin/chown vmail:vmail /var/lib/nethserver/sieve-scripts/*.svbin
fi

exit 0
