---
language: ruby
services:
    - docker
branches:
    only:
        - master

env:
   global:
    - DEST_ID=core
    - NSVER=7
    - DOCKER_IMAGE=nethserver/makerpms:${NSVER}
    - >
        EVARS="
        -e DEST_ID
        -e TRAVIS_BRANCH
        -e TRAVIS_BUILD_ID
        -e TRAVIS_PULL_REQUEST_BRANCH
        -e TRAVIS_PULL_REQUEST
        -e TRAVIS_REPO_SLUG
        -e TRAVIS_TAG
        -e NSVER
        -e VERSIONS_PACK
        -e STAGES_PACK
        -e ENDPOINTS_PACK
        "

before_install:
  # Fix https://github.com/travis-ci/travis-ci/issues/8982#issuecomment-354357640
  - python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'

install:
  - bash prep-sources &> /dev/null

script: >
    docker run -ti --name makerpms ${EVARS}
    --hostname b${TRAVIS_BUILD_NUMBER}.nethserver.org
    --volume $PWD:/srv/makerpms/src:ro ${DOCKER_IMAGE} makerpms-travis -s *.spec
    && docker commit makerpms nethserver/build
    && docker run -ti ${EVARS}
    -e SECRET
    -e SECRET_URL
    -e AUTOBUILD_SECRET
    -e AUTOBUILD_SECRET_URL
    nethserver/build uploadrpms-travis
