#!/usr/bin/perl -w

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::Build::CreateLinks qw(:all);


my @templates = qw(
    /etc/rspamd/local.d/metadata_exporter.conf
    /etc/rspamd/local.d/settings.conf
);

#
# UPDATE event
#

my $event = 'nethserver-mail-quarantine-update';

event_templates($event,
    @templates
);

event_actions($event, qw(
    initialize-default-databases 00
));

event_services($event, qw(
    rspamd restart
));

#
# SAVE event
#

$event = 'nethserver-mail-quarantine-save';

event_templates($event,
    @templates
);

event_services($event, qw(
    rspamd reload
));
