#!/usr/bin/perl

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use esmith::Build::CreateLinks qw(:all);

#--------------------------------------------------
# actions for nethserver-mail2-p3scan-update event
#--------------------------------------------------

my $event = "nethserver-mail2-p3scan-update";
templates2events("/etc/p3scan/p3scan.conf", $event);
event_services($event, qw(
   p3scan restart
));
event_actions($event, 'initialize-default-databases' => '00');
event_actions($event, 'firewall-adjust' => '20');

#
# nethserver-p3scan-save event
#

event_templates('nethserver-p3scan-save', qw(
    /etc/p3scan/p3scan.conf
));
event_actions('nethserver-p3scan-save', qw(
    firewall-adjust 20
));
event_services('nethserver-p3scan-save', qw(
    p3scan restart
));