#!/usr/bin/perl

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use esmith::Build::CreateLinks qw(:all);

my $event = 'nethserver-mail-disclaimer-update';
event_actions ( $event, 'initialize-default-databases' => '00');
event_templates($event,'/etc/postfix/disclaimer');
event_templates($event,'/etc/postfix/master.cf');
event_templates($event, '/etc/postfix/main.cf');
event_services($event, 'postfix' => 'restart');

# expand the script
for $event (qw(domain-create domain-delete domain-modify))
{
event_templates($event,'/etc/postfix/disclaimer');
}
