#!/usr/bin/perl -w
#
# Copyright (C) 2016 Nethesis S.r.l.
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks  qw(:all);

#--------------------------------------------------
# actions for nethserver-getmail-update event
#--------------------------------------------------

$event = "nethserver-getmail-update";
event_actions($event, 
     'initialize-default-databases' => '00',
     'nethserver-getmail-conf' => '20',
);
event_templates($event, qw(
     /etc/cron.d/getmail
     /etc/dovecot/dovecot.conf
));
event_services($event, qw(
    dovecot restart
));


#--------------------------------------------------
# actions for nethserver-getmail-save event
#--------------------------------------------------
$event = "nethserver-getmail-save";
event_actions($event, 
     'nethserver-getmail-conf' => '20',
);
event_templates($event, qw(
     /etc/cron.d/getmail
));


#--------------------------------------------------
# actions for migration-import event
#--------------------------------------------------

$event = "migration-import";
event_actions($event,
     'nethserver-getmail-migrate' => '30'
);


#--------------------------------------------------
# actions for post-restore-config event
#--------------------------------------------------

$event = "post-restore-config";
event_actions($event,
     'nethserver-getmail-migrate-ns6' => '80'
);

