#!/bin/bash

# Prepare source for RPM build

# download langs from transifex

# tar directory
set -e

NODE_OPTIONS="--openssl-legacy-provider"
export NODE_OPTIONS
pushd ui
npm install
npm run build
popd

tar -C ui/dist -c -z -f nethserver-mail-ui.tar.gz .
