#!/usr/bin/perl

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;

use esmith::DomainsDB;
use esmith::ConfigDB;

my $domainsDb = esmith::DomainsDB->open() or die("Could not open DomainsDB!\n");
my $configDb = esmith::ConfigDB->open() or die("Could not open ConfigDB!\n");

my $domainName = $configDb->get_value('DomainName');

if($domainName && $domainsDb->get($domainName)) {
    exit(0);
}

#
# Create and initialize the default domain record for Local Delivery
#
$domainsDb->set_prop($domainName, 'TransportType', 'LocalDelivery', type => 'domain');
$domainsDb->set_prop($domainName, 'UnknownRecipientsActionType', 'bounce');
$domainsDb->set_prop($domainName, 'UnknownRecipientsActionDeliverMailbox', '');
$domainsDb->set_prop($domainName, 'AlwaysBccStatus', 'disabled');
$domainsDb->set_prop($domainName, 'AlwaysBccAddress', '');
$domainsDb->set_prop($domainName, 'DisclaimerStatus', 'disabled');
$domainsDb->set_prop($domainName, 'Description', '');
