#!/bin/bash

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

# Exit immediately if quota plugin is not enabled
if ! doveconf mail_plugins | grep -q -E '\bquota\b'; then
    exit 0
fi

# Exit here if username is passed as second argument
if [[ -n "$2" ]]; then
    exec /usr/bin/doveadm quota recalc -u $2
fi

# Recalc quota for any existing user
cd /var/lib/nethserver/vmail

find . -maxdepth 3 -name 'maildirsize' | (
    IFS=/
    while read SKIPA USER SKIPB; do
        doveadm quota recalc -u ${USER} || :
    done
)
