#!/bin/bash

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

. /usr/libexec/nethserver/api/lib/helper_functions

data=$(cat /dev/stdin)
action=$(echo $data | jq -r '.action')

function _get
{
    field=$1
    echo $data | jq -r ".$field"
}


case $action in

    "run")
        name=$(_get name)
        unit=cockpit-getmail-"$name"

        # Skip double execution
        systemctl is-active $unit &>/dev/null
        if [ $? -eq 0 ]; then
            exit 0
        else
            systemctl reset-failed $unit &>/dev/null
        fi

        systemd-run --setenv=HOME=/root --unit=$unit /usr/libexec/nethserver/api/nethserver-mail/connectors/getmail-wrapper "$name" &>/dev/null
        echo -e "{\"unit\":\"$unit\"}"
        ;;

esac
