#!/usr/bin/perl

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use warnings;
use esmith::ConfigDB;
use JSON;
use NethServer::ApiTools;
use File::Temp;

require '/usr/libexec/nethserver/api/nethserver-mail/lib/mail_functions.pl';

my $input = NethServer::ApiTools::readInput();
my $cmd = $input->{'action'};

my $ret = {};

if ($cmd eq 'list') {
    $ret->{'connectors'} = [];
    my %accounts;
    my $expand = $input->{'expand'} || 0;
    my $gdb = esmith::ConfigDB->open_ro('getmail');
    if ($gdb) {
        foreach my $gr ($gdb->get_all()) {
            my $obj = {'type' => 'getmail', 'name' => $gr->key, 'props' => {}};
            my %props = $gr->props;
            my $account = $props{'Account'};
            $account =~ s/(\@.*)$//;

            if (!$accounts{$account}) {
                $accounts{$account} = [];
            }
            $obj->{'props'} = \%props;
            push($accounts{$account}, $obj);
        }
    }

    $ret->{'connectors'}  = \%accounts;

} elsif ($cmd eq 'check-credentials') {

    my $work_dir = File::Temp->newdir();
    my $mbox = File::Temp->new(DIR => $work_dir->dirname);
    my $conf = File::Temp->new(DIR => $work_dir->dirname);
    my ($name,$passwd,$uid,$gid,$quota,$comment,$gcos,$dir,$shell,$expire) = getpwnam("vmail");
    chown($uid, $gid, $conf->filename);
    chown($uid, $gid, $mbox->filename);

    print $conf "[retriever]\n";
    print $conf "type = ".$input->{'Retriever'}."\n";
    print $conf "server = ".$input->{'Server'}."\n";
    print $conf "username = ".$input->{'Username'}."\n";
    print $conf "password = ".$input->{'Password'}."\n";
    print $conf "[destination]\n";
    print $conf "type = Mboxrd\n";
    print $conf "path = ".$mbox->filename."\n";
    print $conf "user = vmail\n";
    # Try to download just few bytes
    print $conf "[options]\n";
    print $conf "max_messages_per_session = 1\n";
    print $conf "max_message_size = 1\n";

    my $out = NethServer::ApiTools::exec_slurp("/usr/bin/getmail", "--getmaildir", $work_dir->dirname, "--rcfile", $conf->filename, "--quiet");

    if ($? > 0){
        NethServer::ApiTools::error("GenericError",$out);
    } else {
        NethServer::ApiTools::success();
    }
} else {
    NethServer::ApiTools::error();
}

print encode_json($ret);
