#!/usr/bin/perl

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;

use NethServer::Password;
use esmith::ConfigDB;

if ( ! -f '/etc/httpd/admin-conf/rspamd.secret') {
    my $cdb = esmith::ConfigDB->open() || die("Could not open ConfigDB");
    my $password = NethServer::Password::store('rspamd');
    $cdb->set_prop('rspamd', 'Password', $password);
    warn("[NOTICE] initializing /etc/httpd/admin-conf/rspamd.secret\n");
    open(my $fh, '|-', '/usr/bin/htpasswd -i -c -m /etc/httpd/admin-conf/rspamd.secret rspamd');
    print $fh "$password\n";
    close($fh);
}
