#!/usr/bin/perl

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use warnings;
use esmith::ConfigDB;
use JSON;

require '/usr/libexec/nethserver/api/lib/helper_functions.pl';
require '/usr/libexec/nethserver/api/nethserver-mail/lib/mail_functions.pl';

my $input = readInput();
my $cmd = $input->{'action'};

my $ret = {};

if ($cmd eq 'stats') {

    my $timespan = $input->{'timespan'} || 'hourly';
    $ret->{'graph'} = read_rspamd("graph?type=$timespan");
    $ret->{'stat'} = read_rspamd("stat");

} elsif ($cmd eq 'configuration') {

    my $db = esmith::ConfigDB->open_ro();
    my $rspamd = $db->get('rspamd');
    if ($rspamd) {
        $ret->{'name'} = 'rspamd';
        my %props = $rspamd->props;
        foreach (keys %props) {
            if ($_ eq 'type') {
                $ret->{'type'} = $props{$_};
            } elsif ($_ =~ m/List/) {
                $ret->{'props'}{$_} = [ split(",",$props{$_}) ];
            } else {
                $ret->{'props'}{$_} = $props{$_};
            }
        }
    }
}

print encode_json($ret);
