#!/usr/bin/perl

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use warnings;
use esmith::ConfigDB;

require '/usr/libexec/nethserver/api/lib/helper_functions.pl';

my $input = readInput();

my $ret = {};

my $db = esmith::ConfigDB->open();
my $rspamd = $db->get('rspamd');

my $props = $input->{'props'};
foreach (keys %$props) {
    next if ($_ eq 'Password');

    my $value = $props->{$_};

    if (($_ =~ m/List/) && ($_ ne 'BlockAttachmentCustomList')) {
        my $arr = $props->{$_};
        $value = join(",",@$arr);
    }

    $db->set_prop('rspamd', $_, $value);
}

# stop rspamd if SpamCheckStatus is disabled
# no more virus check or attachment  filter

my $SpamCheckStatus = $input->{'props'}->{'SpamCheckStatus'};
if ($SpamCheckStatus eq 'enabled') {
    $db->set_prop('rspamd', 'status', 'enabled');
} else {
    $db->set_prop('rspamd', 'status', 'disabled');
}

system("/sbin/e-smith/signal-event -j nethserver-mail-filter-save");
