#!/usr/bin/perl
#
# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use NethServer::ApiTools;
use strict;
use warnings;
my $input = NethServer::ApiTools::readInput();

my $hostname = $input->{'hostname'};
my $username = $input->{'username'};
my $name = $input->{'name'};
my $password = $input->{'password'};
my $Port = $input->{'Port'};
my $Security = $input->{'Security'};

# find the correct encryption
my $crypt;
if ($input->{Security} eq 'tls') {
    $crypt = '--tls1';
} elsif ($input->{Security} eq 'ssl') {
    $crypt = '--ssl1';
} else {
    $crypt = '';
}


my @imapsync =("imapsync","--host2","localhost","--port2","143","--tls2","--user2",
    $name.'*vmail',"--passfile2","/var/lib/nethserver/imapsync/vmail.pwd","--host1",$hostname,
    "--port1",$Port,$crypt,"--user1",$username,"--password1",$password,"--timeout1","10","--justlogin","--nolog");

system(@imapsync);

if ($?) {
    NethServer::ApiTools::error();
} else {
    NethServer::ApiTools::success();
}
