#!/usr/bin/perl

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use esmith::ConfigDB;
use JSON;

my $cdb = esmith::ConfigDB->open_ro();

my $ret = {};

for (qw(SenderValidation HeloHost SystemUserRecipientStatus)) {
    $ret->{$_} = $cdb->get_prop('postfix', $_);
}

my $policy = $cdb->get_prop('postfix','AccessPolicies');
if (index($policy,'trustednetworks') >= 0) {
    $ret->{'AccessPoliciesTrustednetworks'} = 1;
} else {
    $ret->{'AccessPoliciesTrustednetworks'} = 0;
}
if (index($policy,'smtpauth') >= 0) {
    $ret->{'AccessPoliciesSmtpauth'} = 1;
} else {
    $ret->{'AccessPoliciesSmtpauth'} = 0;
}

$ret->{'AccessBypassList'} = [split(/,/, $cdb->get_prop('postfix','AccessBypassList'))];

#ConnectionsLimit=0
#ConnectionsLimitPerIp=0
#MessageSizeMin=1048576

print encode_json($ret);
