#!/bin/bash

#
# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

#
# nethserver-mail-server
#
# Create the diffie hellman 2048 bit of postfix
#

if [[ -f '/etc/pki/dovecot/private/postfix.dh.param' ]]; then
    exit 0
fi

/usr/bin/openssl dhparam -out /etc/pki/dovecot/private/postfix.dh.param.tmp 2048 > /dev/null 2>&1

if [[ $? != 0 ]];then
    exit 1;
fi

/usr/bin/mv -f /etc/pki/dovecot/private/postfix.dh.param.tmp /etc/pki/dovecot/private/postfix.dh.param
/usr/bin/chown root:root /etc/pki/dovecot/private/postfix.dh.param
/usr/bin/chmod 600 /etc/pki/dovecot/private/postfix.dh.param

if [[ $? != 0 ]];then
    exit 1;
fi


/usr/bin/systemctl reload postfix
