#!/bin/bash

#
# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

#
# nethserver-mail-server
#
# Create the diffie hellman 2048 bit of postfix
#
# The DH group could be renewed from time to time for security concerns.

umask	077

tmpdir=$(mktemp -d /tmp/create-DH2048.XXXXXXX)

# If we exit early, clean up intermediate files:
trap "rm -rf ${tmpdir}" EXIT


/usr/bin/openssl dhparam -out ${tmpdir}/postfix.dh.param 2048 2> /dev/null

if [[ $? != 0 ]];then
    exit 1;
fi

/usr/bin/mv -f ${tmpdir}/postfix.dh.param /etc/pki/dovecot/private/postfix.dh.param

if [[ $? != 0 ]];then
    exit 1;
fi

/usr/bin/systemctl reload postfix

